"""Added image Shop

Revision ID: 15848161d004
Revises: 829ef476950a
Create Date: 2020-05-23 23:03:58.994392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15848161d004'
down_revision = '829ef476950a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('imgurl', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'imgurl')
    # ### end Alembic commands ###
