"""Added Image and Serialization

Revision ID: 3e0b3354bd5d
Revises: f2b7279a02ba
Create Date: 2020-05-25 14:58:44.040956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0b3354bd5d'
down_revision = 'f2b7279a02ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('imgurl', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'imgurl')
    # ### end Alembic commands ###
