"""added SHOP table

Revision ID: 829ef476950a
Revises: db89372f2487
Create Date: 2020-05-20 20:53:22.059454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ef476950a'
down_revision = 'db89372f2487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_email'), 'shop', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_email'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
